name = "Social Agent Based Modelling"
authors = ["Annika Stechemesser <stechemesser@pik-potsdam.de>, Max Kotz <maxkotz@pik-potsdam.de>, Lennart Quante <quante@pik-potsdam.de>"]

[deps]
Agents = "46ada45e-f475-11e8-01d0-f70cc89e6671"
DrWatson = "634d3b9d-ee7a-5ddf-bec9-22491ea816e1"
